### ISSUE TITLE
Responsive Hud/base layout

### ISSUE THREAD

**Issue by MattSurabian** [bocoup/rwd-game-boiler#9]
- fullscreen, across devices
 - vertical/horizontal centering

**Comment by Wilto** [comment]
This is a tricky issue. Taken to its logical extreme, we’re building a configurable responsive _framework_. Since the usual RWD “content-out” approach doesn’t actually apply here—since the game developer will dictate content _and_ layouts—we’re left building a set of “sensible” defaults for individual components and configuration options. The tricky part is making them mix-and-match-able moreso than building the baseline layouts/modules.

The goal is to compromise with a few simple defaults, establish the means of configuring/overriding them,  and document extensively.

This ticket can be considered fulfilled once a “minimum viable” layout framework has been PR’d against the primary codebase.
